CREATE TABLE order_table (
                             order_number int primary key ,
                             total_amount double precision,
                             order_date date
);

CREATE TABLE order_item (
                            id int GENERATED BY DEFAULT AS IDENTITY,
                            item_name varchar(32),
                            quantity int,
                            order_id int references order_table(order_number)
);
