CREATE TABLE order_manage (
                             order_number int primary key ,
                             total_amount double precision,
                             order_date date
);

CREATE TABLE order_item (
                            id int GENERATED BY DEFAULT AS IDENTITY,
                            item_name varchar(32),
                            quantity int,
                            order_id int,
                            CONSTRAINT fk_order_fk
                                FOREIGN KEY (order_id)
                                    REFERENCES order_manage(order_number)
);
